project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    left:
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
      - icon: linkedin
        href: https://www.linkedin.com/in/matthew-huang-67b835231/
      - icon: github
        href: https://github.com/Ambrois
format:
  html:
    theme: slate

editor: source
