project:
  type: website
  output-dir: docs

website:
  bread-crumbs: false
  sidebar:
    style: floating
    search: false
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: index.qmd
        contents:
          - text: "Black Hole Simulation"
            href: projects/blackholesim/index.qmd
          - text: "Data Visualization Gallery"
            href: projects/visualizations/index.qmd
          - text: "Bayesian Analysis"
            href: projects/bayesian/index.rmd
          - text: "Statistical Consulting"
            href: projects/senior_consulting/index.qmd
            contents:
              - text: "IBaby"
                href: projects/senior_consulting/ibaby.qmd
              - text: "Sustainability"
                href: projects/senior_consulting/sustainability.qmd
              - text: "Mobility"
                href: projects/senior_consulting/mobility.qmd
          - text: "ML Experiments"
            href: projects/ml_experiments/index.qmd
            contents:
              - text: "Skin Cancer"
                href: projects/ml_experiments/skincancer.qmd
              - text: "Tuned Lens"
                href: projects/ml_experiments/tunedlens.qmd


format:
  html:
    theme: cosmo

editor: source
